### ISSUE TITLE
Does not work with Relay 1.5

### ISSUE THREAD

**Issue by rybon** [danielholmes/relay-compiler-webpack-plugin#21]
`Module not found: TypeError: _this5._reporter.reportMessage is not a function`

Happens when updating these dependencies to 1.5:

```
babel-plugin-relay    1.4.1   1.4.1   1.5.0
react-relay           1.4.1   1.4.1   1.5.0
relay-compiler        1.4.1   1.4.1   1.5.0
relay-runtime         1.4.1   1.4.1   1.5.0
```

Reverting to 1.4.1 works as expected.

**Comment by graingert** [comment]
@rybon fixed in `@procensus/relay-compiler-webpack-plugin`

**Comment by rybon** [comment]
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error: Unexpected Name "FRAGMENT"

**Comment by danielholmes** [comment]
@rybon Can you provide your schema or any extra info?

**Comment by rybon** [comment]
It's a private project so unfortunately I can't. Sorry about that.

But when I run:
```
./node_modules/relay-compiler/bin/relay-compiler --schema=./schema.graphql --src=./src --extensions=jsx
```
it does work.

**Comment by galki** [comment]
with 0.7.0 I also got
```
Module not found: TypeError: _this5._reporter.reportMessage is not a function
```
and after upgrading to 0.8.0 
```
GraphQLError: Syntax Error GraphQL request (5:36) Cannot parse the unexpected character "&".
```
perhaps its related to the new graphql-js upgrade to 0.13.0: https://github.com/graphql/graphql-js/issues/1246#event-1483843705

**Comment by danielholmes** [comment]
I've got a small example project here running with the latest version: https://github.com/danielholmes/relay-compiler-webpack-plugin-example . It's doesn't have an exhaustive coverage of graphql features, but does include fragments which @rybon 's above error mentioned. 

@rybon I was able to replicate your error when using uppercase fragment instead of lowercase. I'll look into it further, but could be a quick fix there if you change it to lower case

**Comment by rybon** [comment]
@danielholmes great, thanks for digging into this issue. I'll give your suggestion a go.

**Comment by koddsson** [comment]
I've got the same error as @rybon. Here's my schema:

```graphql
type Query {
  user(userId: Int!): User
}

type User {
  id: ID!
  username: String!
  fullName: String
}
```

And here is how I'm making `graphql` queries:

```js
import React from 'react'
import {createFragmentContainer, graphql} from 'react-relay'

const Hello = ({fullName}) => React.createElement('h1', null, `Hello ${fullName}`)

export default createFragmentContainer(Hello, {
  data: graphql`
    fragment src_data on User {
      fullName
    }
  `
})
```

Removing these lines fixes it:

https://github.com/danielholmes/relay-compiler-webpack-plugin/blob/505598b3be382662757207e39c08b52ab5bae94c/src/getSchema.js#L18-L23

Are these lines needed? I can make a quick PR to remove these if not. I also think maybe the error message might send people down the wrong path since it assumes that there is something wrong with the schema when we've injected some extra stuff into it.

**Comment by koddsson** [comment]
I ended up moving them into the if-branch than handles JSON files since they seem to be have been added to handle some case for those. That also might be why this has been hard to reproduce?

https://github.com/danielholmes/relay-compiler-webpack-plugin-example uses json schemas it seems so this could be why we couldn't figure this out?

**Comment by danielholmes** [comment]
@rybon I was able to replicate your case with @koddsson 's help. I've published a new version v0.9.0 which fixed my issue - let me know if you still have problems with that

**Comment by rybon** [comment]
It's working now, thanks a lot! Really appreciate the help from everyone involved on this.
