### PR TITLE
move json specific logic into if statement

### LINKED ISSUE #21: Does not work with Relay 1.5
`Module not found: TypeError: _this5._reporter.reportMessage is not a function`

Happens when updating these dependencies to 1.5:

```
babel-plugin-relay    1.4.1   1.4.1   1.5.0
react-relay           1.4.1   1.4.1   1.5.0
relay-compiler        1.4.1   1.4.1   1.5.0
relay-runtime         1.4.1   1.4.1   1.5.0
```

Reverting to 1.4.1 works as expected.

### PR DESCRIPTION
**Pull request by koddsson**
I'm not a 100% sure on what these lines do but it seems that these lines where added to do handle JSON schema files.

>[Adds support for handling json schema files with the introspection query result format.](https://github.com/MainframeHQ/relay-compiler-webpack-plugin/pull/1)

I moved them into the if branch where JSON schema files are handled and that fixes #21 for me 😺

### CODE REVIEW

**Comment by danielholmes** [comment]
Thanks for this @koddsson . You led me down the track of what _I think_ is the full solution - changes in keywords in graphql versions: https://github.com/facebook/relay/commit/e75a614318c35d910be9312d6c83837620647dac#diff-963195b963363400090e8be11ea89bcf . This change fixes it for me, I'm going to apply it and publish a new version shortly

**Comment by koddsson** [comment]
>changes in keywords in graphql versions: facebook/relay@e75a614#diff-963195b963363400090e8be11ea89bcf

I was thinking something like that was happening since `FIELD` worked fine! Thanks for the help! I'll try out 0.9.0
